global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zander-ingestion'
    scheme: http
    static_configs:
      - targets: ['jubilant-warmth.railway.internal:8080']
    metrics_path: '/metrics'
